=encoding utf8

=head1 ABOUT

This repository contains user-contributed subtitles for the videos of
the Daily Grace channel on YouTube (
L<http://www.youtube.com/user/dailygrace> ).

=head1 LICENSE

The text of the subtitles is based on the utterances from the videos and is
likely copyright by
L<http://www.mydamnchannel.com/channel/daily_grace_1047.aspx> (“All Rights
Reserved”/etc.).

=cut

